alias reload=". ~/.bash_profile"
alias 1="cd -"
alias ..="cd .."
alias ...="cd ../.."
alias l="ls -CF"
alias ll="ls -lF"
alias la="ls -AF"
alias lla="ls -AlhF"
alias lns="ln -s"
alias rmr="rm -rf"
alias pu="pushd"
alias po="popd"
alias o="open"
alias k9="killall -9"
alias h="history"

# vim
alias v="vim"
alias vi="v"
alias vu="v +BundleInstall +qall"

# tmux
alias tm="tmux"
alias tmn="tmux new -s"
alias tml="tmux ls"
alias tma="tmux a -t"

# ios
alias ios="open /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Applications/iPhone\ Simulator.app"

# git
alias st="git status -sb"
alias g="git"
alias ga="git add"
alias gco="git checkout"
alias gcob="git checkout -b"
alias gc="git commit -m"
alias gd="git diff"
alias gd1="git diff HEAD~1"
alias gdom="git diff master origin/master"
alias gdc="git diff --cached --name-only"
alias gl="git log --pretty='format:%Cgreen%h%Creset %an - %s' --graph"
alias gm="git merge --no-ff"
alias gmom="git merge origin/master"
alias gpom="git pull origin master"
alias gp="git push"
alias gpu="git push -u"
alias gr="git rebase"
alias grit="git rebase -i"
alias grh="git reset --hard"
alias grf="git reset HEAD"
alias gsno="git show --name-only"
alias gsh="git show --pretty=short --stat"
alias gst="git stash --keep-index"
alias gsp="git stash pop"
